#!/bin/bash
# samtools merge -f /mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/hiseq-paired.merge.bam /mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/hiseq-paired/musschenbroekiiWGA_CAATTA_L008_001.fastp.decon.unmerged.bam /mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/hiseq-paired/musschenbroekii-WGA_CAATTA_L007_001.fastp.decon.unmerged.bam /mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/hiseq-paired/musschenbroekiiWGA_CAATTA_L008_001.fastp.decon.merged.bam /mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/hiseq-paired/musschenbroekii-WGA_CAATTA_L007_001.fastp.decon.merged.bam &> /mnt/beegfs/gt156213e/murinae-seq/01-Assembly-scripts/logs/06.5-Post-map-logs/Maxomys-musschenbroekii-hiseq-paired-merge-mouse.log
# samtools merge -f /mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/hiseq2500-paired.merge.bam /mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/hiseq2500-paired/lane2_CAATTA_001.fastp.decon.unmerged.bam /mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/hiseq2500-paired/lane2_CAATTA_001.fastp.decon.merged.bam &> /mnt/beegfs/gt156213e/murinae-seq/01-Assembly-scripts/logs/06.5-Post-map-logs/Maxomys-musschenbroekii-hiseq2500-paired-merge-mouse.log
# picard -Xmx10g MarkDuplicates I=/mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/hiseq-paired.merge.bam TMP_DIR=/mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/tmp O=/mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/hiseq-paired.merge.mkdup.bam M=/mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/Maxomys-musschenbroekii-hiseq-paired-mkdup-metrics.txt CREATE_INDEX=true &> /mnt/beegfs/gt156213e/murinae-seq/01-Assembly-scripts/logs/06.5-Post-map-logs/Maxomys-musschenbroekii-hiseq-paired-mkdup-mouse.log
# picard -Xmx10g MarkDuplicates I=/mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/hiseq2500-paired.merge.bam TMP_DIR=/mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/tmp O=/mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/hiseq2500-paired.merge.mkdup.bam M=/mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/Maxomys-musschenbroekii-hiseq2500-paired-mkdup-metrics.txt CREATE_INDEX=true &> /mnt/beegfs/gt156213e/murinae-seq/01-Assembly-scripts/logs/06.5-Post-map-logs/Maxomys-musschenbroekii-hiseq2500-paired-mkdup-mouse.log
#samtools merge -f /mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/Maxomys-musschenbroekii.bam /mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/hiseq-paired.merge.mkdup.bam /mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/hiseq2500-paired.merge.mkdup.bam &> /mnt/beegfs/gt156213e/murinae-seq/01-Assembly-scripts/logs/06.5-Post-map-logs/Maxomys-musschenbroekii-merge-mouse.log
samtools index /mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/Maxomys-musschenbroekii.bam
#samtools depth -b /mnt/beegfs/gt156213e/murinae-seq/Targets/targets-mm10-coords.bed /mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/Maxomys-musschenbroekii.bam > /mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/Maxomys-musschenbroekii-depth.tab
#samtools stats -d -r /mnt/beegfs/gt156213e/ref-genomes/mm10/mm10.fa /mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/Maxomys-musschenbroekii.bam > /mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/Maxomys-musschenbroekii-stats.txt
#samtools flagstat /mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/Maxomys-musschenbroekii.bam > /mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/Maxomys-musschenbroekii-flagstats.txt
mosdepth -x -b /mnt/beegfs/gt156213e/murinae-seq/Targets/targets-mm10-coords.bed /mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/Maxomys-musschenbroekii /mnt/beegfs/gt156213e/murinae-seq/01-Assembly-data/06-Map/Maxomys-musschenbroekii-mouse/Maxomys-musschenbroekii.bam &> /mnt/beegfs/gt156213e/murinae-seq/01-Assembly-scripts/logs/06.5-Post-map-logs/Maxomys-musschenbroekii-mosdepth-mouse.log
