---
#title: "Exome assembly stats"
#author: "gwct"
#date: "11/21/2019"
output: 
  html_document:
    includes:
      in_header: '../html-chunks/rmd_header.html'
    df_print: paged
    code_folding: hide
---

```{r setup, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(ggbeeswarm)
library(ggpubr)
source("../lib/design.r")

targets = 203198
target_avg_len = 267.5448577249776
target_min_len = 100
target_total_len = 54364580

tiles = 470359
tile_avg_len = 109.8747
tile_min_len = 57
tile_total_len = 51679441
# Target and tile info

htmltools::includeHTML("../html-chunks/nav.html")
```

# Exome assembly stats with Spades

```{r fig1, out.width="100%", fig.align="center"}
spades_data = read.csv("../../../data/exome-assemblies.csv", header=TRUE)
#spades_data$batch = as.character(spades_data$batch)
spades_data$batch = factor(spades_data$batch, levels=c("G1.1", "G1.2", "G1.3", "G1.4", "G1.5", "C1.5", "G2.1", "G2.2", "G2.3", "G2.4"))

####################
# Spades contig count distributions by batch
scaff_batch_p = ggplot(spades_data, aes(x=batch, y=count, fill=batch)) +
  geom_hline(yintercept=targets, linetype=2, size=1, color="#666666") +
  geom_hline(yintercept=tiles, linetype=2, size=1, color="#9494b8") +
  geom_violin(width=1, color="#666666", size=0.3) +
  geom_quasirandom(size=0.75, alpha=0.6, width=0.15, color="#999999") +
  scale_fill_manual(labels=c("Original 40 G1", "Rattus 8 G1", "Mus 14 G1", "New 70 G1", "Aussie 46 G1", "Aussie 46 C1", "Original 40 G2", "Rattus 8 G2", "Mus 14 G2", "New 70 G2"),
                     values=c("#920000", "#333333", "#006ddb", "#db6d00", "#b66dff", "#b66dff", "#920000", "#333333", "#006ddb", "#db6d00")) +
  annotate("text", x=1.1, y=targets-10000, label="# targets", color="#666666", size=4) +
  annotate("text", x=0.9, y=tiles-10000, label="# tiles", color="#9494b8", size=4) +
  #ggtitle("Spades assembly counts") +
  labs(x="Sequencing batch", y="# Scaffolds") +
  scale_x_discrete(labels=c("Original 40 G1", "Rattus 8 G1", "Mus 14 G1", "New 70 G1", "Aussie 46 G1", "Aussie 46 C1", "Original 40 G2", "Rattus 8 G2", "Mus 14 G2", "New 70 G2")) +
  bartheme() + 
  theme(legend.position="none",
        axis.text.x = element_text(angle=25, hjust=1))

print(scaff_batch_p)
```

```{r fig2, out.width="100%", fig.align = "center"}
####################
# Spades length distributions, by batch
len_batch_p2 = ggplot(spades_data, aes(x=batch, y=avg.len, fill=batch)) +
  geom_hline(yintercept=target_avg_len, linetype=2, size=1, color="#666666") +
  geom_hline(yintercept=target_min_len, linetype=2, size=1, color="#666666") +
  geom_hline(yintercept=tile_avg_len, linetype=2, size=1, color="#9494b8") +
  geom_hline(yintercept=tile_min_len, linetype=2, size=1, color="#9494b8") +
  geom_violin(width=1, color="#666666", size=0.3) +
  geom_quasirandom(size=1, alpha=0.6, width=0.15, color="#999999") +
  scale_fill_manual(labels=c("Original 40 G1", "Rattus 8 G1", "Mus 14 G1", "New 70 G1", "Aussie 46 G1", "Aussie 46 C1", "Original 40 G2", "Rattus 8 G2", "Mus 14 G2", "New 70 G2"),
                     values=c("#920000", "#333333", "#006ddb", "#db6d00", "#b66dff", "#b66dff", "#920000", "#333333", "#006ddb", "#db6d00")) +
  annotate("text", x=1.4, y=target_avg_len-25, label="Avg. target len", color="#666666", size=4) +
  annotate("text", x=1.4, y=target_min_len-20, label="Min. target len", color="#666666", size=4) +
  annotate("text", x=9.5, y=tile_avg_len+35, label="Avg. tile len", color="#9494b8", size=4) +
  annotate("text", x=9.5, y=tile_min_len-15, label="Min. tile len", color="#9494b8", size=4) +
  #ggtitle("Spades assembly counts") +
  labs(x="Sequencing batch", y="Avg. scaffold length") +
  scale_x_discrete(labels=c("Original 40 G1", "Rattus 8 G1", "Mus 14 G1", "New 70 G1", "Aussie 46 G1", "Aussie 46 C1", "Original 40 G2", "Rattus 8 G2", "Mus 14 G2", "New 70 G2")) +
  bartheme() +
  theme(legend.position="none",
        axis.text.x = element_text(angle=25, hjust=1))

print(len_batch_p2)
```

```{r footer}
cat("Page last updated:", format(Sys.time(), "%m/%d/%Y %H:%M:%S %Z"))
htmltools::includeHTML("../html-chunks/rmd_footer.html")
```