---
#title: "Exome trees"
#author: "gwct"
#date: "06/19/2021"
output: 
  html_document:
    includes:
      in_header: '../html-chunks/rmd_header.html'
    df_print: paged
    code_folding: hide
---

```{r setup, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(ggplot2)
#library(cowplot)
library(ggbeeswarm)
#library(ggpubr)
library(dplyr)
#library(kableExtra)
library(tidyr)
library(ggtree)
library(phytools)
library(phangorn)
library(reshape2)
library(ggExtra)
library(ggrepel)
library(vroom)
#source("../lib/design.r")
source("C:/bin/core/corelib/design.r")
source("C:/bin/core/get_tree_info.r")

htmltools::includeHTML("../html-chunks/rmd_nav.html")
```

# Full coding species tree

188 species. 11,775 coding loci. Gene trees reconstructed with IQ-tree and species topology with ASTRAL (no tip branch lengths).

```{r read, out.width="100%", fig.align = "center", warning=FALSE}
tree_type = "astral"

tree_file = "../../data/trees/full_coding_iqtree_astral.cf.rooted.tree"
astral_tree = read.tree(tree_file)

tree_info_astral = treeToDF(astral_tree)
tree_info_astral = tree_info_astral %>% separate(label, c("astral", "gcf", "scf"), sep="/", remove=F)
tree_info_astral$astral[tree_info_astral$node.type=="tip"] = NA
tree_info_astral$astral = as.numeric(tree_info_astral$astral)
tree_info_astral$gcf = as.numeric(tree_info_astral$gcf)
tree_info_astral$scf = as.numeric(tree_info_astral$scf)
# Read astral tree data

concat_file = "../../data/trees/full_coding_iqtree_concat.cf.rooted.tree"
concat_tree = read.tree(concat_file)

tree_info_concat = treeToDF(concat_tree)
tree_info_concat = tree_info_concat %>% separate(label, c("bootstrap", "gcf", "scf"), sep="/", remove=F)
tree_info_concat$bootstrap[tree_info_concat$node.type=="tip"] = NA
tree_info_concat$bootstrap = as.numeric(tree_info_concat$bootstrap)
tree_info_concat$gcf = as.numeric(tree_info_concat$gcf)
tree_info_concat$scf = as.numeric(tree_info_concat$scf)
# Read concat tree data

rf = RF.dist(concat_tree, astral_tree)

#write.csv(tree_info, "../../data/trees/full-coding-concat-cf-rooted.csv", row.names=F)

if(tree_type == "astral"){
  tree_info = tree_info_astral
  rodent_tree = astral_tree
  xmax = 31
}else if(tree_type == "concat"){
  tree_info = tree_info_concat
  rodent_tree = concat_tree
  xmax = 0.125
}

```

```{r fig1, out.width="100%", fig.align = "center", warning=FALSE, fig.height=16}
h = corecol(numcol=1, pal="wilke", offset=3)
l = corecol(numcol=1, offset=3)
# Colors

gcf_tree = ggtree(rodent_tree, size=0.8, ladderize=F, aes(color=tree_info$gcf)) +
  scale_color_continuous(name='gCF', low=l, high=h, limits=c(0,100)) +
  xlim(0, xmax) +
  geom_tiplab(color="#333333", fontface='italic', size=2) +
  theme(legend.position=c(0.05,0.9))
#geom_text(aes(label=rodent_data$support), hjust=-.1, color="#006ddb") +
#geom_nodepoint(color="#666666", alpha=0.85, size=4)
print(gcf_tree)
#ggsave("../data/trees/gcf-tree.pdf", gcf_tree, width=8, height=16, unit="in")
# gCF tree
```

```{r fig2, out.width="100%", fig.align = "center", warning=FALSE, fig.height=16}
h = corecol(numcol=1, pal="wilke", offset=3)
l = corecol(numcol=1, offset=3)
# Colors

scf_tree = ggtree(rodent_tree, size=0.8, ladderize=F, aes(color=tree_info$scf)) +
  scale_color_continuous(name='sCF', low=l, high=h, limits=c(0,100)) +
  xlim(0, xmax) +
  geom_tiplab(color="#333333", fontface='italic', size=2) +
  theme(legend.position=c(0.05,0.9))
#geom_text(aes(label=rodent_data$support), hjust=-.1, color="#006ddb") +
#geom_nodepoint(color="#666666", alpha=0.85, size=4)
print(scf_tree)
#ggsave("../data/trees/scf-tree.pdf", scf_tree, width=8, height=16, unit="in")
# sCF tree
```

```{r fig3, out.width="50%", fig.align = "center", warning=FALSE}
h = corecol(numcol=1, pal="wilke", offset=3)
l = corecol(numcol=1, offset=3)
# Colors

if(tree_type == "astral"){
  p = ggplot(tree_info, aes(x=gcf, y=scf, color=astral)) + 
    geom_point() +
    scale_color_continuous(name='Astral support', low=l, high=h, limits=c(0.8,1))
}else if(tree_type == "concat"){
  p = ggplot(tree_info, aes(x=gcf, y=scf, color=bootstrap)) + 
    geom_point() +
    scale_color_continuous(name='Bootstrap', low=l, high=h, limits=c(0,100))
}
p = p + bartheme() +
  theme(legend.title=element_text(size=12))
print(p)
```

# Average rates per gene with basic model fit (mg94-local)

```{r read-mg94local, out.width="50%", fig.align = "center", warning=FALSE}
mg94_local_file_gz = gzfile("../../data/rates/full-coding-mg94-local.csv.gz")
mg94_local = vroom(mg94_local_file_gz, comment="#")

mg94_local_gene = group_by(mg94_local, file) %>% summarize(dn=mean(dn, na.rm=T), ds=mean(ds, na.rm=T), dn.ds=mean("dn/ds", na.rm=T), nonsynonymous.bl=mean("nonsynonymous bl", na.rm=T), synonymous.bl=mean("synonymous bl", na.rm=T))

p = ggplot(subset(mg94_local_gene, ds < 0.05), aes(x=ds, y=dn)) +
  geom_point(size=2, alpha=0.2, color="#333333") +
  #geom_smooth(method="lm", se=F, ) +
  xlab("Avg. dS per gene") + 
  ylab("Avg. dN per gene") + 
  bartheme()
p = ggExtra::ggMarginal(p, type="histogram", bins=50, fill=corecol(pal="wilke", numcol=1), color="#666666")
print(p)
```

```{r fig4, out.width="50%", fig.align = "center", warning=FALSE, eval=FALSE}
ds_p = ggplot(subset(mg94_local_gene, ds < 0.05), aes(x=ds)) +
  geom_histogram(bins=50, fill=corecol(pal="wilke", numcol=1), color="#666666") +
  scale_y_continuous(expand=c(0,0)) +
  xlab("dS") +
  ylab("# of genes") +
  bartheme()
print(ds_p)
# Distribution of dS when using concatenated tree
```

```{r fig5, out.width="50%", fig.align = "center", warning=FALSE, eval=FALSE}
dn_p = ggplot(mg94_local_gene, aes(x=dn)) +
  geom_histogram(bins=50, fill=corecol(pal="wilke", numcol=1), color="#666666") +
  scale_y_continuous(expand=c(0,0)) +
  xlab("dN") +
  ylab("# of genes") +
  bartheme()
print(dn_p)
# Distribution of dS when using gene trees
```
```{r ds_filter, out.width="50%", fig.align = "center", warning=FALSE}
ds_filter_level = 0.03

ds_filter = subset(mg94_local_gene, ds > ds_filter_level)$file
# Get a list of genes to filter out in subsequent analyses based on dS

print(paste("Removing", length(ds_filter), "genes with dS above", ds_filter_level, "from subsequent analyses."))

#write.csv(ds_filter, file="../../data/rates/mg94-local-ds-filter-0.03.csv", row.names=F)
```
## Average rates per branch with basic model fit
```{r ds_branch_avgs, out.width="50%", fig.align = "center", warning=FALSE}
if(tree_type == "astral"){
  tree_rates = read.csv("../../data/rates/full-coding-astral-cf-rooted-rates.csv", header=T)
}else if(tree_type == "concat"){
  tree_rates = read.csv("../../data/rates/full-coding-concat-cf-rooted-rates.csv", header=T)
}
p = ggplot(tree_rates, aes(x=avg.ds, y=avg.dn)) +
  geom_point(size=2, alpha=0.2, color="#333333") +
  geom_text_repel(aes(label=ifelse(avg.ds>0.2|avg.dn>0.01,as.character(node),''))) +
  #geom_smooth(method="lm", se=F, ) +
  xlab("Avg. dS per branch") + 
  ylab("Avg. dN per branch") + 
  bartheme()
p = ggExtra::ggMarginal(p, type="histogram", bins=50, fill=corecol(pal="wilke", numcol=1, offset=1), color="#666666")
print(p)

tree_rates$ds.outlier = ifelse(tree_rates$avg.ds>0.2,tree_rates$node,'')
tree_rates$dn.outlier = ifelse(tree_rates$avg.dn>0.01,tree_rates$node,'')
```

```{r fig6, out.width="50%", fig.align = "center", warning=FALSE}

full_clade = select(tree_rates, clade, node.type, num.genes.full)
full_clade$label = "Full clade"
names(full_clade)[3] = "num.genes"

partial_clade = select(tree_rates, clade, node.type, num.genes.partial)
partial_clade$label = "Partial clade"
names(partial_clade)[3] = "num.genes"

no_clade = select(tree_rates, clade, node.type, num.genes.no.clade)
no_clade$label = "Discordant/missing clade"
names(no_clade)[3] = "num.genes"

clade_counts = rbind(full_clade, partial_clade, no_clade)

branch_counts = ggplot(clade_counts, aes(x=label, y=num.genes, group=label, color=node.type)) +
  geom_quasirandom(size=2, width=0.25, alpha=0.25) +
  geom_boxplot(outlier.shape=NA, alpha=0.15, width=0.5, color="#666666") +
  #geom_point(data=p_means, aes(x=label, y=post.codon.aln.length), size=2, color="red") +
  #geom_line(data=p_means, aes(x=label, y=post.codon.aln.length), size=2, color="blue") +
  ylab("Sequence length (bp)") +
  xlab("") +
  bartheme() +
  theme(axis.text.x = element_text(angle=25, hjust=1))
print(branch_counts)
```


```{r fig7, out.width="100%", fig.align = "center", warning=FALSE, fig.height=16}
h = corecol(numcol=1, pal="wilke", offset=1)
l = corecol(numcol=1, offset=1)

rate_tree = ggtree(rodent_tree, size=0.8, ladderize=F, aes(color=tree_rates$avg.ds)) +
  scale_color_continuous(name='Avg. dS', low=l, high=h, limits=c(0,0.9)) +
  xlim(0, xmax) +
  geom_tiplab(color="#333333", fontface='italic', size=2) +
  theme(legend.position=c(0.05,0.9)) +
  geom_label(aes(x=branch, label=ifelse(tree_rates$avg.ds>0.2,as.character(node),'')), label.size=NA, fill="transparent")
  #geom_text(aes(label=node), hjust=-.1, color="#006ddb")
#geom_nodepoint(color="#666666", alpha=0.85, size=4)
print(rate_tree)
```

```{r fig8, out.width="100%", fig.align = "center", warning=FALSE, fig.height=16}
h = corecol(numcol=1, pal="wilke", offset=1)
l = corecol(numcol=1, offset=1)

rate_tree = ggtree(rodent_tree, size=0.8, ladderize=F, aes(color=tree_rates$avg.dn)) +
  scale_color_continuous(name='Avg. dN', low=l, high=h, limits=c(0,0.015)) +
  xlim(0, xmax) +
  geom_tiplab(color="#333333", fontface='italic', size=2) +
  theme(legend.position=c(0.05,0.9)) +
  geom_label(aes(x=branch, label=ifelse(tree_rates$avg.dn>0.01,as.character(node),'')), label.size=NA, fill="transparent")
#geom_text(aes(label=rodent_data$support), hjust=-.1, color="#006ddb") +
#geom_nodepoint(color="#666666", alpha=0.85, size=4)
print(rate_tree)
```

## Basic rate and phenotype correlations with tip branches

```{r read_pheno, out.width="100%", fig.align = "center", warning=FALSE}
pheno = read.csv("../../data/phenotype-data/combined-phenotype-data.csv", header=T, comment.char="#")
tips = subset(tree_rates, node.type=="tip")
names(tips)[2] = "sample"
pheno_rates = merge(pheno, tips, by="sample")

pheno_rates = select(pheno_rates, sample, Adult_Mass.g., Total_Length.mm., Head.Body_Length.mm., Tail_Length.mm., Hind_Foot_Length.mm., Relative_Tail_Length, Relative_Hind_Foot_Length, avg.dn, avg.ds, avg.dn.ds)

pheno_rates_long = melt(pheno_rates, id.vars=c("sample", "avg.dn", "avg.ds", "avg.dn.ds"))

#pheno_rates_long = gather(pheno_rates, sample, value, Adult_Mass.g., Total_Length.mm., Head.Body_Length.mm., Tail_Length.mm., Hind_Foot_Length.mm., Relative_Tail_Length, Relative_Hind_Foot_Length)
```

```{r fig9, out.width="75%", fig.align = "center", warning=FALSE, fig.height=8}
p = ggplot(pheno_rates_long, aes(x=value, y=avg.ds)) +
  geom_point(size=2, alpha=0.2, color="#333333") +
  geom_smooth(method="lm", se=F, linetype="dashed", color=corecol(numcol=1, pal="wilke", offset=2)) +
  xlab("Avg. trait value per tip") +
  ylab("Avg. dS per tip") +
  facet_wrap(~variable, scales="free_x") +
  bartheme()
print(p)
```

```{r fig10, out.width="75%", fig.align = "center", warning=FALSE, fig.height=8}
p = ggplot(pheno_rates_long, aes(x=value, y=avg.dn)) +
  geom_point(size=2, alpha=0.2, color="#333333") +
  geom_smooth(method="lm", se=F, linetype="dashed", color=corecol(numcol=1, pal="wilke", offset=2)) +
  xlab("Avg. trait value per tip") +
  ylab("Avg. dN per tip") +
  facet_wrap(~variable, scales="free_x") +
  bartheme()
print(p)
```

```{r footer}
cat("Page last updated:", format(Sys.time(), "%m/%d/%Y %H:%M:%S %Z"))
htmltools::includeHTML("../html-chunks/rmd_footer.html")
```