def get():    
    seq_run_ids = {
        'nextseq-single-1' : 0,
        'nextseq-single-2' : 1,
        'nextseq-paired-1' : 2,
        'nextseq-paired-2' : 3,
        'miseq-paired' : 4,
        # Orig 38
        'hiseq-paired' : 5,
        'hiseq2500-paired' : 6,
        # Orig rattus
        'hiseq2000-paired-1' : 7,
        'hiseq2000-paired-2' : 8,
        # Mus
        'hiseq4000-paired-1' : 9,
        'hiseq4000-paired-2' : 10,
        # New
        'seq-run-1' : 11,
        'seq-run-2' : 12,
        'seq-run-3' : 13,
        'seq-run-4' : 14
        # From Box -- only Pseudomys higginsi has seq runs 3 and 4??
    }

    spec_ids = {
        "Apomys lubangensis" : ['30', '30', 'JAE169', '1', 'JAE169', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Batomys salomonseni" : ['31', '31', 'JAE3320', '2', 'JAE3320', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Bulimus bagobus" : ['32', '32', 'JAE1712', '3', 'JAE1712', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Chrotomys mindorensis" : ['33', '33', 'JAE520', '4', 'JAE520', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Phloeomys pallidus" : ['34', '34', 'JEC43', '5', 'JEC43', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Rhynchomys isarogensis" : ['35', '35', 'JAE2195', '6', 'JAE2195', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Sundamys meulleri" : ['36', '36', 'JAE1283', '7', 'JAE1283', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Taeromys punicans" : ['37', '37', 'JLP25862', '8', 'JLP25862', 'NA', 'NA', 'NA', 'NA','SM077','NA','NA','NA','NA','NA'],
        "Hyorhinomys stuempkei" : ['38', '38', 'JAE4661', '9', 'JAE4661', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Hybomys univittatus" : ['39', '39', 'TCD4026', '10', 'TCD4026', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Colomys goslingi" : ['40', '40', 'TCD4175', '11', 'TCD4175', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Malacomys longipes" : ['41', '41', 'TCD4253', '12', 'TCD4253', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Hylomyscus vulcanorum" : ['42', '42', 'TCD4382', '13', 'TCD4382', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Praomys degraaffi" : ['43', '43', 'TCD4312', '14', 'TCD4312', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Grammomys sp" : ['44', '44', 'TCD4560', '15', 'TCD4560', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Lemniscomys striatus" : ['45', '45', 'TCD4711', '16', 'TCD4711', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Berylymys bowersi" : ['46', '46', 'ABTC116431', '17', 'ABTC116431', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Crunomys celebensis" : ['47', '47', 'Z21894', '18', 'Z21894', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Echiothrix centrosa" : ['48', '48', 'Z27993', '19', 'Z27993', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Gracillimus radix" : ['49', '49', 'Z08508', '20', 'Z08508', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Leopoldomys sabanus" : ['50', '50', 'Z25191', '21', 'Z25191', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Margaretamys parvus" : ['51', '51', 'Z21794', '22', 'Z21794', 'NA', 'NA', 'NA', 'NA','SM062','NA','NA','NA','NA','NA'],
        "Melasmothrix naso" : ['52', '52', 'Z21808', '23', 'Z21808', 'NA', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Paucidentomys vermidax" : ['53', '53', 'Z21914', '24', 'Z21914', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Sommeromys macrorhinos" : ['54', '54', 'Z21740', '25', 'Z21740', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Tateomys macrocercus" : ['55', '55', 'Z21834', '26', 'Z21834', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Tateomys rhinogradoides" : ['56', '56', 'Z21785', '27', 'Z21785', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Waiomys mamasae" : ['57', '57', 'Z20624', '28', 'Z20624', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Chiropodomys gliroides" : ['58', '58', 'Z25153', '29', 'Z25153', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Lorentzimys nouhuysi" : ['59', '59', 'ABTC-46314', '30', 'ABTC-46314', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Mastacomys fuscus" : ['60', '60', 'ABTC-07354', '31', 'ABTC-07354', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Melomys rufescens" : ['61', '61', 'ABTC-44798', '32', 'ABTC-44798', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Hydromys chrysogaster" : ['62', '62', 'Z5248', '33', 'Z5248', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Apodemus sylvaticus" : ['63', '63', 'SMG3823', '34', 'SMG3823', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Archboldomys luzonensis" : ['64', '64', 'EAR1826', '35', 'EAR1826', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Bunomys chrysocomus" : ['65', '65', 'JAE4867', '36', 'JAE4867', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Haeromys minahassae" : ['66', '66', 'JAE4996', '37', 'JAE4996', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Maxomys surifer" : ['67', '67', 'JAE3632', '38', 'JAE3632', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Niviventer lepturus" : ['68', '68', 'JAE4746', '39', 'JAE4746', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Paruromys dominator" : ['69', '69', 'JAE4870', '40', 'JAE4870', 'NA', 'NA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Bunomys andrewsi" : ['NA', 'NA', 'NA', 'NA', 'NA', 'andrewsii', 'GATGCC', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Rattus exulans" : ['NA', 'NA', 'NA', 'NA', 'NA', 'exulans', 'TGACGT', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Rattus hoffmanni" : ['NA', 'NA', 'NA', 'NA', 'NA', 'hoffmani', 'CCGATT', 'NA', 'NA','NA','SM074','NA','NA','NA','NA'],
        "Rattus leucopus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'leucopus', 'ATGCCG', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Rattus lutreolus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'lutreolus', 'CAATAT', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Maxomys musschenbroekii" : ['NA', 'NA', 'NA', 'NA', 'NA', 'musschenbroekii', 'CAATTA', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Rattus praetor" : ['NA', 'NA', 'NA', 'NA', 'NA', 'praetor', 'CAGTAC', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Rattus villosissimus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'vilosissimus', 'AGATAG', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Rattus hoffmanni (no WGA)" : ['NA', 'NA', 'NA', 'NA', 'NA', 'hoffmani (no WGA)', 'GATCTC', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Rattus exulans (no WGA)" : ['NA', 'NA', 'NA', 'NA', 'NA', 'exulans (no WGA)', 'GCATTG', 'NA', 'NA','NA','NA','NA','NA','NA','NA'],
        "Mus musculus reference" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', '10460X5', 'GCAAGA','NA','NA','NA','NA','NA','NA'],
        "Mus musculus musculus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', '10460X14', 'TTGGAT','NA','NA','NA','NA','NA','NA'],
        # CZII
        "Mus musculus domesticus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', '10460X15', 'CGACCT','NA','NA','NA','NA','NA','NA'],
        # Lewes
        "Mus musculus castaneus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', '10460X7', 'CTCGAT','NA','NA','NA','NA','NA','NA'],
        "Mus caroli" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', '10460X9', 'ACCAAC','NA','NA','NA','NA','NA','NA'],
        "Mus cervicolor" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', '10460X10', 'CCGGTA','NA','NA','NA','NA','NA','NA'],
        "Mus cookii" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', '10460X3', 'CCTAGG','NA','NA','NA','NA','NA','NA'],
        "Mus macedonicus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', '10460X12', 'TTGAAG','NA','NA','NA','NA','NA','NA'],
        "Mus minutoides" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', '10460X2', 'CTCTGC','NA','NA','NA','NA','NA','NA'],
        "Mus molossinus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', '10460X8', 'GCTCGA','NA','NA','NA','NA','NA','NA'],
        "Mus pahari" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', '10460X1', 'TCGCAG','NA','NA','NA','NA','NA','NA'],
        "Mus platythrix" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', '10460X13', 'ACTATC','NA','NA','NA','NA','NA','NA'],
        "Mus spicilegus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', '10460X11', 'AACTCC','NA','NA','NA','NA','NA','NA'],
        "Mus spretus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', '10460X4', 'GGATCA','NA','NA','NA','NA','NA','NA'],
        "Coccymys ruemmleri" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM033', 'NA','NA','NA','NA','NA'],
        "Grammomys dryas" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC8', 'NA','NA','NA','NA','NA'],
        "Carpomys melanurus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM085', 'NA','NA','NA','NA','NA'],
        "Crateromys heaneyi" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC4', 'NA','NA','NA','NA','NA'],
        "Dasymys montanus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM086', 'NA','NA','NA','NA','NA'],
        "Aethomys hindei" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC1', 'NA','NA','NA','NA','NA'],
        "Hylomyscus stella" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC10', 'NA','NA','NA','NA','NA'],
        "Anisomys imitator" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM008', 'NA','NA','NA','NA','NA'],
        "Crunomys melanius" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC5', 'NA','NA','NA','NA','NA'],
        "Niviventer rapit" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM056', 'NA','NA','NA','NA','NA'],
        "Phloeomys cumingii" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM069', 'NA','NA','NA','NA','NA'],
        "Aethomys nyikae" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM084', 'NA','NA','NA','NA','NA'],
        "Hybomys planifrons" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM040', 'NA','NA','NA','NA','NA'],
        "Pogonomys macrourus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM071', 'NA','NA','NA','NA','NA'],
        "Musseromys anacuao" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM063', 'NA','NA','NA','NA','NA'],
        "Limnomys sibuanus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM089', 'NA','NA','NA','NA','NA'],
        "Pithecheir melanurus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM070', 'NA','NA','NA','NA','NA'],
        "Thamnomys sp." : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC24', 'NA','NA','NA','NA','NA'],
        "Mammelomys lanosus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM047', 'NA','NA','NA','NA','NA'],
        "Xenuromys barbatus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM010', 'NA','NA','NA','NA','NA'],
        "Hydromys sp nov" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC9', 'NA','NA','NA','NA','NA'],
        "Xeromys myoides" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM080', 'NA','NA','NA','NA','NA'],
        "Pseudohydromys ellermani" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM073', 'NA','NA','NA','NA','NA'],
        "Leptomys elegans" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM044', 'NA','NA','NA','NA','NA'],
        "Pelomys isseli" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM068', 'NA','NA','NA','NA','NA'],
        "Mus pos_ctrl_F" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'M44_F11', 'NA','NA','NA','NA','NA'],
        "Mus pos_ctrl_E" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'M44_E11', 'NA','NA','NA','NA','NA'],
        "Niviventer bukit" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM054', 'NA','NA','NA','NA','NA'],
        "Genus sp nov" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM059', 'NA','NA','NA','NA','NA'],
        "Saxatilomys paulinae" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM075', 'NA','NA','NA','NA','NA'],
        "Crunomys sp." : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC6', 'NA','NA','NA','NA','NA'],
        "Microhydromys richardsoni" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM050', 'NA','NA','NA','NA','NA'],
        "Uromys caudimaculatus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM078', 'NA','NA','NA','NA','NA'],
        "Mirzamys louiseae" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM051', 'NA','NA','NA','NA','NA'],
        "Papagomys armandvillei" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM057', 'NA','NA','NA','NA','NA'],
        "Chiromyscus chiropus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM034', 'NA','NA','NA','NA','NA'],
        "Pogonomelomys bruijni" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC26', 'NA','NA','NA','NA','NA'],
        "Paraleptomys sp" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM065', 'NA','NA','NA','NA','NA'],
        "Oenomys hypoxanthus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC13', 'NA','NA','NA','NA','NA'],
        "Bandicota indica" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM009', 'NA','NA','NA','NA','NA'],
        "Rattus xanthurus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC17', 'NA','NA','NA','NA','NA'],
        "Lenomys meyeri" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC11', 'NA','NA','NA','NA','NA'],
        "Thamnomys kempi" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC23', 'NA','NA','NA','NA','NA'],
        "Parahydromys asper" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM058', 'NA','NA','NA','NA','NA'],
        "Rattus argentiventer" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM042', 'NA','NA','NA','NA','NA'],
        "Uromys sp nov" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC25', 'NA','NA','NA','NA','NA'],
        "Otomys tropicalis" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC15', 'NA','NA','NA','NA','NA'],
        "Niviventer cremoriventer" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM055', 'NA','NA','NA','NA','NA'],
        "Otomys denti" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC14', 'NA','NA','NA','NA','NA'],
        "Praomys jacksoni" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC31', 'NA','NA','NA','NA','NA'],
        "Mus pos_ctrl_C" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'M44_C11', 'NA','NA','NA','NA','NA'],
        "Mus pos_ctrl_B" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'M44_B11', 'NA','NA','NA','NA','NA'],
        "Mus pos_ctrl_D1" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'M44_D11', 'NA','NA','NA','NA','NA'],
        "Margaretamys christinae" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM061','NA','NA','NA','NA'],
        "Dasymys incomtus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC29','NA','NA','NA','NA'],
        "Taeromys callitrichus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC19','NA','NA','NA','NA'],
        "Hybomys lunaris" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM039','NA','NA','NA','NA'],
        "Sundamys annandalei" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC18','NA','NA','NA','NA'],
        "Nesokia indica" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM053','NA','NA','NA','NA'],
        "Macruromys major" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM045','NA','NA','NA','NA'],
        "Mus musculoides" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC30','NA','NA','NA','NA'],
        "Pelomys minor" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC16','NA','NA','NA','NA'],
        "Tarsomys apoensis" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC21','NA','NA','NA','NA'],
        "Batomys russatus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC28','NA','NA','NA','NA'],
        "Halmaheramys bokimekot" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC22','NA','NA','NA','NA'],
        "Chiruromys vates" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM035','NA','NA','NA','NA'],
        "Chrotomys whiteheadi" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC34','NA','NA','NA','NA'],
        "Abeomelomys sevia" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC32','NA','NA','NA','NA'],
        "Berylmys mackenzii" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM011','NA','NA','NA','NA'],
        "Solomys salebrosus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM076','NA','NA','NA','NA'],
        "Zelotomys woosnami" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM081','NA','NA','NA','NA'],
        "Kadarsanomys sodyi" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC_27','NA','NA','NA','NA'],
        "Mallomys rothschildi" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM046','NA','NA','NA','NA'],
        "Taeromys taerae" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'REC20','NA','NA','NA','NA'],
        "Vandeleuria oleracea" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'SM079','NA','NA','NA','NA'],
        "Mus pos_ctrl_A" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'M44_A12','NA','NA','NA','NA'],
        "Mus pos_ctrl_G" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'M44_G11','NA','NA','NA','NA'],
        "Mus pos_ctrl_D2" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'M44_D11','NA','NA','NA','NA'],
        "Conilurus albipes" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA','53930_HTVLKBCX2_TGCGTCC','53930_HTVLKBCX2_TGCGTCC', 'NA', 'NA'],
        "Conilurus penicillatus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA','53920_HTVLWBCX2_GCTCGAA','53920_HTVLWBCX2_GCTCGAA', 'NA', 'NA'],
        "Leggadina forresti" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA','52918_AH7T2JBCX2_CTGCGAC','52918_AH7T7NBCX2_CTGCGAC', 'NA', 'NA'],
        "Leggadina lakedownensis" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA','52919_AH7T2JBCX2_ACGTATG','52919_AH7T7NBCX2_ACGTATG', 'NA', 'NA'],
        "Mesembriomys gouldii" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA','53919_HTVLKBCX2_CTCGATG','53919_HTVLKBCX2_CTCGATG', 'NA', 'NA'],
        "Mesembriomys macrurus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA','53918_HTVLWBCX2_ATGGAGA','53918_HTVLWBCX2_ATGGAGA', 'NA', 'NA'],
        "Notomys alexis" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA','52920_AH7T2JBCX2_ATACTGA','52920_AH7T7NBCX2_ATACTGA', 'NA', 'NA'],
        "Notomys amplus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA','53926_HTVLWBCX2_TTGGATC','53926_HTVLWBCX2_TTGGATC', 'NA', 'NA'],
        "Notomys aquilo" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA','52921_AH7T2JBCX2_TACTTAG','52921_AH7T7NBCX2_TACTTAG', 'NA', 'NA'],
        "Notomys cervinus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA','52922_AH7T2JBCX2_AAGCTAA','52922_AH7T7NBCX2_AAGCTAA', 'NA', 'NA'],
        "Notomys fuscus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA','52924_AH7T2JBCX2_AGAAGAC','52924_AH7T7NBCX2_AGAAGAC', 'NA', 'NA'],
        "Notomys longicaudatus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA','52956_BH7T33BCX2_GGTCAAG','52956_BH7T77BCX2_GGTCAAG', 'NA', 'NA'],
        "Notomys macrotis" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA','53929_HTVLKBCX2_AGGTACC','53929_HTVLKBCX2_AGGTACC', 'NA', 'NA'],
        "Notomys mitchellii" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA','53916_HTVLWBCX2_GGATCAA','53916_HTVLWBCX2_GGATCAA', 'NA', 'NA'],
        "Pseudomys patrius" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA','52940_BH7T33BCX2_CCAACCT','52940_BH7T77BCX2_CCAACCT', 'NA', 'NA'],
        "Pseudomys pilligaensis" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA','52942_BH7T33BCX2_AGAATTA','52942_BH7T77BCX2_AGAATTA', 'NA', 'NA'],
        "Pseudomys shortridgei" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA','53914_HTVLWBCX2_CTCTGCA','53914_HTVLWBCX2_CTCTGCA1', 'NA', 'NA'],
        "Rattus colletti" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA','52951_BH7T33BCX2_GCTAATC','52951_BH7T77BCX2_GCTAATC', 'NA', 'NA'],
        "Rattus tunneyi" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA','52952_BH7T33BCX2_GACTTCT','52952_BH7T77BCX2_GACTTCT', 'NA', 'NA'],
        "Zyzomys argurus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA','52946_BH7T33BCX2_AACGACC','52946_BH7T77BCX2_AACGACC', 'NA', 'NA'],
        "Zyzomys maini" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA','52947_BH7T33BCX2_CCAGCGG','52947_BH7T77BCX2_CCAGCGG', 'NA', 'NA'],
        "Zyzomys palatalis" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA','52949_BH7T33BCX2_TGGCAAT','52949_BH7T77BCX2_TGGCAAT', 'NA', 'NA'],
        "Zyzomys pedunculatus" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA','52948_BH7T33BCX2_TAGTTCC','52948_BH7T77BCX2_TAGTTCC', 'NA', 'NA'],
        "Zyzomys woodwardi" : ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA','52950_BH7T33BCX2_CGTATAT','52950_BH7T77BCX2_CGTATAT', 'NA', 'NA'],
        "Pseudomys albocinereus" : [ "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "52930_AH7T2JBCX2_AACCTGC", "52930_AH7T7NBCX2_AACCTGC", "NA", "NA" ],
        "Pseudomys apodemoides" : [ "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "52931_AH7T2JBCX2_GACGATT", "52931_AH7T7NBCX2_GACGATT", "NA", "NA" ],
        "Pseudomys auritus" : [ "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "53928_HTVLKBCX2_TAATGCG", "53928_HTVLWBCX2_TAATGCG", "NA", "NA" ],
        "Pseudomys australis" : [ "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "52932_AH7T2JBCX2_TAGGCCG", "52932_AH7T7NBCX2_TAGGCCG", "NA", "NA" ],
        "Pseudomys bolami" : [ "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "53922_HTVLKBCX2_CCGGTAC", "53922_HTVLWBCX2_CCGGTAC", "NA", "NA" ],
        "Pseudomys calabyi" : [ "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "52938_BH7T33BCX2_AATAAGC", "52938_BH7T77BCX2_AATAAGC", "NA", "NA" ],
        "Pseudomys chapmani" : [ "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "52926_AH7T2JBCX2_TCAGCTT", "52926_AH7T7NBCX2_TCAGCTT", "NA", "NA" ],
        "Pseudomys delicatulus" : [ "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "52944_BH7T33BCX2_TTCTAGG", "52944_BH7T77BCX2_TTCTAGG", "NA", "NA" ],
        "Pseudomys desertor" : [ "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "52925_AH7T2JBCX2_GTCCGGC", "52925_AH7T7NBCX2_GTCCGGC", "NA", "NA" ],
        "Pseudomys fieldi" : [ "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "52941_BH7T33BCX2_GCAGAAG", "52941_BH7T77BCX2_GCAGAAG", "NA", "NA" ],
        "Pseudomys fumeus" : [ "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "52955_BH7T33BCX2_AGCAGGT", "52955_BH7T77BCX2_AGCAGGT", "NA", "NA" ],
        "Pseudomys gouldii" : [ "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "52955_BH7T33BCX2_AGCAGGT", "52955_BH7T77BCX2_AGCAGGT", "NA", "NA" ],
        "Pseudomys gracilicaudatus" : [ "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "52934_AH7T2JBCX2_TTCAACC", "52934_AH7T7NBCX2_TTCAACC", "NA", "NA" ],
        "Pseudomys hermannsburgensis" : [ "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "52943_BH7T33BCX2_CAGCATC", "52943_BH7T77BCX2_CAGCATC", "NA", "NA" ],
        "Pseudomys higginsi" : [ "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "52953_BH7T33BCX2_GTACTAT", "52953_BH7T77BCX2_GTACTAT", "53925_HTVLKBCX2_ACTATCA", "53925_HTVLWBCX2_ACTATCA" ],
        "Pseudomys johnsoni" : [ "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "52935_AH7T2JBCX2_TTAACTC", "52935_AH7T7NBCX2_TTAACTC", "NA", "NA" ],
        "Pseudomys nanus" : [ "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "52936_AH7T2JBCX2_TAGTCTA", "52936_AH7T7NBCX2_TAGTCTA", "NA", "NA" ],
        "Pseudomys novaehollandiae" : [ "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "53927_HTVLKBCX2_CGACCTG", "53927_HTVLWBCX2_CGACCTG_", "NA", "NA" ],
        "Pseudomys occidentalis" : [ "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "52939_BH7T33BCX2_AGCCTTG", "52939_BH7T77BCX2_AGCCTTG", "NA", "NA" ],
        "Pseudomys oralis" : [ "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "NA", "52928_AH7T2JBCX2_GCCTACG", "52928_AH7T7NBCX2_GCCTACG", "NA", "NA" ]
    };

    specs_ordered = ["Apomys lubangensis", "Batomys salomonseni", "Bulimus bagobus", "Chrotomys mindorensis", "Phloeomys pallidus", "Rhynchomys isarogensis", "Sundamys meulleri", "Taeromys punicans",
                        "Hyorhinomys stuempkei", "Hybomys univittatus", "Colomys goslingi", "Malacomys longipes", "Hylomyscus vulcanorum", "Praomys degraaffi", "Grammomys sp", "Lemniscomys striatus",
                        "Berylymys bowersi", "Crunomys celebensis", "Echiothrix centrosa", "Gracillimus radix", "Leopoldomys sabanus", "Margaretamys parvus", "Melasmothrix naso", "Paucidentomys vermidax",
                        "Sommeromys macrorhinos", "Tateomys macrocercus", "Tateomys rhinogradoides", "Waiomys mamasae", "Chiropodomys gliroides", "Lorentzimys nouhuysi", "Mastacomys fuscus", "Melomys rufescens",
                        "Hydromys chrysogaster", "Apodemus sylvaticus", "Archboldomys luzonensis", "Bunomys chrysocomus", "Haeromys minahassae", "Maxomys surifer", "Niviventer lepturus", "Paruromys dominator",
                        "Bunomys andrewsi", "Rattus exulans", "Rattus hoffmanni", "Rattus leucopus", "Rattus lutreolus", "Maxomys musschenbroekii", "Rattus praetor", "Rattus villosissimus", "Rattus hoffmanni (no WGA)",
                        "Rattus exulans (no WGA)", "Mus musculus reference", "Mus musculus musculus", "Mus musculus domesticus", "Mus musculus castaneus", "Mus caroli", "Mus cervicolor", "Mus cookii",
                        "Mus macedonicus", "Mus minutoides", "Mus molossinus", "Mus pahari", "Mus platythrix", "Mus spicilegus", "Mus spretus", "Coccymys ruemmleri", "Grammomys dryas", "Carpomys melanurus",
                        "Crateromys heaneyi", "Dasymys montanus", "Aethomys hindei", "Hylomyscus stella", "Anisomys imitator", "Crunomys melanius", "Niviventer rapit", "Phloeomys cumingii", "Aethomys nyikae",
                        "Hybomys planifrons", "Pogonomys macrourus", "Musseromys anacuao", "Limnomys sibuanus", "Pithecheir melanurus", "Thamnomys sp.", "Mammelomys lanosus", "Xenuromys barbatus", "Hydromys sp nov",
                        "Xeromys myoides", "Pseudohydromys ellermani", "Leptomys elegans", "Pelomys isseli", "Mus pos_ctrl_F", "Mus pos_ctrl_E", "Niviventer bukit", "Genus sp nov", "Saxatilomys paulinae",
                        "Crunomys sp.", "Microhydromys richardsoni", "Uromys caudimaculatus", "Mirzamys louiseae", "Papagomys armandvillei", "Chiromyscus chiropus", "Pogonomelomys bruijni",
                        "Paraleptomys sp", "Oenomys hypoxanthus", "Bandicota indica", "Rattus xanthurus", "Lenomys meyeri", "Thamnomys kempi", "Parahydromys asper", "Rattus argentiventer", "Uromys sp nov",
                        "Otomys tropicalis", "Niviventer cremoriventer", "Otomys denti", "Praomys jacksoni", "Mus pos_ctrl_C", "Mus pos_ctrl_B", "Mus pos_ctrl_D1", "Margaretamys christinae",
                        "Dasymys incomtus", "Taeromys callitrichus", "Hybomys lunaris", "Sundamys annandalei", "Nesokia indica", "Macruromys major", "Mus musculoides", "Pelomys minor",
                        "Tarsomys apoensis", "Batomys russatus", "Halmaheramys bokimekot", "Chiruromys vates", "Chrotomys whiteheadi", "Abeomelomys sevia", "Berylmys mackenzii", "Solomys salebrosus",
                        "Zelotomys woosnami", "Kadarsanomys sodyi", "Mallomys rothschildi", "Taeromys taerae", "Vandeleuria oleracea", "Mus pos_ctrl_A", "Mus pos_ctrl_G", "Mus pos_ctrl_D2", "Conilurus albipes NMV c7585", 
                        "Conilurus penicillatus M14056", "Leggadina forresti WAMM62323", "Leggadina lakedownensis WAMM21623", "Leporillus apicalis C90", "Leporillus conditor ABTC13335", "Mastacomys fuscus M13957", 
                        "Mastacomys fuscus NMV C37546", "Mesembriomys gouldii ABTC7449", "Mesembriomys macrurus ABTC7337", "Notomys alexis U1308", "Notomys amplus NMV C512", "Notomys aquilo M 32455", "Notomys cervinus M22857", 
                        "Notomys fuscus M22830", "Notomys longicaudatus C6278", "Notomys macrotis ZD 1841 1167", "Notomys mitchelli ABTC94521", "Notomys mitchellii M21518", "Pseudomys patrius JM10865", 
                        "Pseudomys pilligaensis ABTC18120", "Pseudomys shortridgei M7890", "Pseudomys shortridgei M62127", "Pseudomys shortridgei Z25113", "Rattus colletti RAT25", "Rattus tunneyi RAT130", 
                        "Zyzomys argurus ABTC61630", "Zyzomys maini ABTC07900", "Zyzomys palatalis ABTC30744", "Zyzomys pedunculatus Z34925", "Zyzomys woodwardi WAMM21724", "Pseudomys albocinereus WAMM18855", 
                        "Pseudomys apodemoides M16672", "Pseudomys auritus 1846 4 4 67", "Pseudomys australis M25541", "Pseudomys bolami ABTC08077", "Pseudomys bolami ABTC107389", "Pseudomys calabyi U4324", 
                        "Pseudomys calabyi WAMM56280", "Pseudomys chapmani WAMM29440", "Pseudomys delicatulus JM18363", "Pseudomys delicatulus M29247", "Pseudomys delicatulus U1509", "Pseudomys delicatulus WAMM29247", 
                        "Pseudomys desertor ABTC41464", "Pseudomys fieldi ABTC08164", "Pseudomys fumeus ABTC08168", "Pseudomys gouldii C955", "Pseudomys gracilicaudatus ABTC08163", "Pseudomys hermannsburgensis ABTC08067", 
                        "Pseudomys higginsi UC1421", "Pseudomys johnsoni ABTC08053", "Pseudomys nanus U1448", "Pseudomys novaehollandiae ABTC08140", "Pseudomys novaehollandiae NMV C22127", "Pseudomys occidentalis ABTC08043", 
                        "Pseudomys oralis RAT7"];

    spec_abbr = {
    # This is out of date/unused since new seqs.
        "Apomys lubangensis" : 'alub',
        "Batomys salomonseni" : 'bsal',
        "Bulimus bagobus" : 'bbag',
        "Chrotomys mindorensis" : 'cmin',
        "Phloeomys pallidus" : 'ppal',
        "Rhynchomys isarogensis" : 'risa',
        "Sundamys meulleri" : 'smeu',
        "Taeromys punicans" : 'tpun',
        "Hyorhinomys stuempkei" : 'hstu',
        "Hybomys univittatus" : 'huni',
        "Colomys goslingi" : 'cgos',
        "Malacomys longipes" : 'mlon',
        "Hylomyscus vulcanorum" : 'hvul',
        "Praomys degraaffi" : 'pdeg',
        "Grammomys sp" : 'gram',
        "Lemniscomys striatus" : 'lstr',
        "Berylymys bowersi" : 'bbow',
        "Crunomys celebensis" : 'ccel',
        "Echiothrix centrosa" : 'ecen',
        "Gracillimus radix" : 'grad',
        "Leopoldomys sabanus" : 'lsab',
        "Margaretamys parvus" : 'mpar',
        "Melasmothrix naso" : 'mnas',
        "Paucidentomys vermidax" : 'pver',
        "Sommeromys macrorhinos" : 'smac',
        "Tateomys macrocercus" : 'tmac',
        "Tateomys rhinogradoides" : 'trhi',
        "Waiomys mamasae" : 'wmam',
        "Chiropodomys gliroides" : 'cgli',
        "Lorentzimys nouhuysi" : 'lnou',
        "Mastacomys fuscus" : 'mfus',
        "Melomys rufescens" : 'mruf',
        "Hydromys chrysogaster" : 'hchr',
        "Apodemus sylvaticus" : 'asyl',
        "Archboldomys luzonensis" : 'aluz',
        "Bunomys chrysocomus" : 'bchr',
        "Haeromys minahassae" : 'hmin',
        "Maxomys surifer" : 'msur',
        "Niviventer lepturus" : 'nlep',
        "Paruromys dominator" : 'pdom',
        "Bunomys andrewsi" : 'band',
        "Rattus exulans" : 'rexu',
        "Rattus hoffmani" : 'rhof',
        "Rattus leucopus" : 'rleu',
        "Rattus lutreolus" : 'rlut',
        "Maxomys musschenbroekii" : 'mxmu',
        "Rattus praetor" : 'rpra',
        "Rattus villosissimus" : 'rvil',
        "Rattus hoffmani (no WGA)" : 'rhof',
        "Rattus exulans (no WGA)" : 'rexu',
        "Mus musculus reference" : 'mmur',
        "Mus musculus musculus" : 'mmus',
        "Mus musculus domesticus" : 'mdom',
        "Mus musculus castaneus" : 'mcas',
        "Mus caroli " : 'mcar',
        "Mus cervicolor" : 'mcer',
        "Mus cookii" : 'mcoo',
        "Mus macedonicus" : 'mmac',
        "Mus minutoides" : 'mmin',
        "Mus molossinus" : 'mmol',
        "Mus pahari" : 'mpah',
        "Mus platythrix" : 'mpla',
        "Mus spicilegus" : 'mspi',
        "Mus spretus" : 'mspr'
    };

    basedirs = [
    # Out of date.
        "/data/raw/3970-JG-0001-30508478/",
        "/data/raw/3970-JG-0001-rerun/3970-JG-0001-30508478/",
        "/data/raw/JG12/",
        "/data/raw/3970-JG-0002-30556548/",
        "/data/raw/20150625_Rat_Capture",
        "/data/raw/usc_20140721/usc_data_june_july_2014/",
        "/data/raw/uoregon_1876/",
        "/data/raw/10460R/Fastq/",
        "/data/raw/uoregon_1875/",
        "/data/raw/Novogene-Dec2019-Exomes-and-SPRET/Capture1-2/H202SC19112857/Rawdata/",
        "/data/raw/Novogene-Dec2019-Exomes-and-SPRET/Capture3/H202SC19112857/Rawdata/"
    ];

    spec_ids_new = {
        "Apomys lubangensis" : {0: '30', 1: '30', 2: 'JAE169', 3: '1', 4: 'JAE169'},
        "Batomys salomonseni" : {0: '31', 1: '31', 2: 'JAE3320', 3: '2', 4: 'JAE3320'},
        "Bulimus bagobus" : {0: '32', 1: '32', 2: 'JAE1712', 3: '3', 4: 'JAE1712'},
        "Chrotomys mindorensis" : {0: '33', 1: '33', 2: 'JAE520', 3: '4', 4: 'JAE520'},
        "Phloeomys pallidus" : {0: '34', 1: '34', 2: 'JEC43', 3: '5', 4: 'JEC43'},
        "Rhynchomys isarogensis" : {0: '35', 1: '35', 2: 'JAE2195', 3: '6', 4: 'JAE2195'},
        "Sundamys meulleri" : {0: '36', 1: '36', 2: 'JAE1283', 3: '7', 4: 'JAE1283'},
        "Taeromys punicans" : {0: '37', 1: '37', 2: 'JLP25862', 3: '8', 4: 'JLP25862', 9: 'SM077'},
        "Hyorhinomys stuempkei" : {0: '38', 1: '38', 2: 'JAE4661', 3: '9', 4: 'JAE4661'},
        "Hybomys univittatus" : {0: '39', 1: '39', 2: 'TCD4026', 3: '10', 4: 'TCD4026'},
        "Colomys goslingi" : {0: '40', 1: '40', 2: 'TCD4175', 3: '11', 4: 'TCD4175'},
        "Malacomys longipes" : {0: '41', 1: '41', 2: 'TCD4253', 3: '12', 4: 'TCD4253'},
        "Hylomyscus vulcanorum" : {0: '42', 1: '42', 2: 'TCD4382', 3: '13', 4: 'TCD4382'},
        "Praomys degraaffi" : {0: '43', 1: '43', 2: 'TCD4312', 3: '14', 4: 'TCD4312'},
        "Grammomys sp" : {0: '44', 1: '44', 2: 'TCD4560', 3: '15', 4: 'TCD4560'},
        "Lemniscomys striatus" : {0: '45', 1: '45', 2: 'TCD4711', 3: '16', 4: 'TCD4711'},
        "Berylymys bowersi" : {0: '46', 1: '46', 2: 'ABTC116431', 3: '17', 4: 'ABTC116431'},
        "Crunomys celebensis" : {0: '47', 1: '47', 2: 'Z21894', 3: '18', 4: 'Z21894'},
        "Echiothrix centrosa" : {0: '48', 1: '48', 2: 'Z27993', 3: '19', 4: 'Z27993'},
        "Gracillimus radix" : {0: '49', 1: '49', 2: 'Z08508', 3: '20', 4: 'Z08508'},
        "Leopoldomys sabanus" : {0: '50', 1: '50', 2: 'Z25191', 3: '21', 4: 'Z25191'},
        "Margaretamys parvus" : {0: '51', 1: '51', 2: 'Z21794', 3: '22', 4: 'Z21794', 9: 'SM062'},
        "Melasmothrix naso" : {0: '52', 1: '52', 2: 'Z21808', 3: '23', 4: 'Z21808'},
        "Paucidentomys vermidax" : {0: '53', 1: '53', 2: 'Z21914', 3: '24', 4: 'Z21914'},
        "Sommeromys macrorhinos" : {0: '54', 1: '54', 2: 'Z21740', 3: '25', 4: 'Z21740'},
        "Tateomys macrocercus" : {0: '55', 1: '55', 2: 'Z21834', 3: '26', 4: 'Z21834'},
        "Tateomys rhinogradoides" : {0: '56', 1: '56', 2: 'Z21785', 3: '27', 4: 'Z21785'},
        "Waiomys mamasae" : {0: '57', 1: '57', 2: 'Z20624', 3: '28', 4: 'Z20624'},
        "Chiropodomys gliroides" : {0: '58', 1: '58', 2: 'Z25153', 3: '29', 4: 'Z25153'},
        "Lorentzimys nouhuysi" : {0: '59', 1: '59', 2: 'ABTC-46314', 3: '30', 4: 'ABTC-46314'},
        "Mastacomys fuscus" : {0: '60', 1: '60', 2: 'ABTC-07354', 3: '31', 4: 'ABTC-07354'},
        "Melomys rufescens" : {0: '61', 1: '61', 2: 'ABTC-44798', 3: '32', 4: 'ABTC-44798'},
        "Hydromys chrysogaster" : {0: '62', 1: '62', 2: 'Z5248', 3: '33', 4: 'Z5248'},
        "Apodemus sylvaticus" : {0: '63', 1: '63', 2: 'SMG3823', 3: '34', 4: 'SMG3823'},
        "Archboldomys luzonensis" : {0: '64', 1: '64', 2: 'EAR1826', 3: '35', 4: 'EAR1826'},
        "Bunomys chrysocomus" : {0: '65', 1: '65', 2: 'JAE4867', 3: '36', 4: 'JAE4867'},
        "Haeromys minahassae" : {0: '66', 1: '66', 2: 'JAE4996', 3: '37', 4: 'JAE4996'},
        "Maxomys surifer" : {0: '67', 1: '67', 2: 'JAE3632', 3: '38', 4: 'JAE3632'},
        "Niviventer lepturus" : {0: '68', 1: '68', 2: 'JAE4746', 3: '39', 4: 'JAE4746'},
        "Paruromys dominator" : {0: '69', 1: '69', 2: 'JAE4870', 3: '40', 4: 'JAE4870'},
        "Bunomys andrewsi" : {5: 'andrewsii', 6: 'GATGCC'},
        "Rattus exulans" : {5: 'exulans', 6: 'TGACGT'},
        "Rattus hoffmanni" : {5: 'hoffmani', 6: 'CCGATT', 10: 'SM074'},
        "Rattus leucopus" : {5: 'leucopus', 6: 'ATGCCG'},
        "Rattus lutreolus" : {5: 'lutreolus', 6: 'CAATAT'},
        "Maxomys musschenbroekii" : {5: 'musschenbroekii', 6: 'CAATTA'},
        "Rattus praetor" : {5: 'praetor', 6: 'CAGTAC'},
        "Rattus villosissimus" : {5: 'vilosissimus', 6: 'AGATAG'},
        "Rattus hoffmanni (no WGA)" : {5: 'hoffmani(noWGA)', 6: 'GATCTC'},
        "Rattus exulans (no WGA)" : {5: 'exulans(noWGA)', 6: 'GCATTG'},
        "Mus musculus reference" : {7: '10460X5', 8: 'GCAAGA'},
        "Mus musculus musculus" : {7: '10460X14', 8: 'TTGGAT'},
        "Mus musculus domesticus" : {7: '10460X15', 8: 'CGACCT'},
        "Mus musculus castaneus" : {7: '10460X7', 8: 'CTCGAT'},
        "Mus caroli" : {7: '10460X9', 8: 'ACCAAC'},
        "Mus cervicolor" : {7: '10460X10', 8: 'CCGGTA'},
        "Mus cookii" : {7: '10460X3', 8: 'CCTAGG'},
        "Mus macedonicus" : {7: '10460X12', 8: 'TTGAAG'},
        "Mus minutoides" : {7: '10460X2', 8: 'CTCTGC'},
        "Mus molossinus" : {7: '10460X8', 8: 'GCTCGA'},
        "Mus pahari" : {7: '10460X1', 8: 'TCGCAG'},
        "Mus platythrix" : {7: '10460X13', 8: 'ACTATC'},
        "Mus spicilegus" : {7: '10460X11', 8: 'AACTCC'},
        "Mus spretus" : {7: '10460X4', 8: 'GGATCA'},
        "Coccymys ruemmleri" : {9: 'SM033'},
        "Grammomys dryas" : {9: 'REC8'},
        "Carpomys melanurus" : {9: 'SM085'},
        "Crateromys heaneyi" : {9: 'REC4'},
        "Dasymys montanus" : {9: 'SM086'},
        "Aethomys hindei" : {9: 'REC1'},
        "Hylomyscus stella" : {9: 'REC10'},
        "Anisomys imitator" : {9: 'SM008'},
        "Crunomys melanius" : {9: 'REC5'},
        "Niviventer rapit" : {9: 'SM056'},
        "Phloeomys cumingii" : {9: 'SM069'},
        "Aethomys nyikae" : {9: 'SM084'},
        "Hybomys planifrons" : {9: 'SM040'},
        "Pogonomys macrourus" : {9: 'SM071'},
        "Musseromys anacuao" : {9: 'SM063'},
        "Limnomys sibuanus" : {9: 'SM089'},
        "Pithecheir melanurus" : {9: 'SM070'},
        "Thamnomys sp." : {9: 'REC24'},
        "Mammelomys lanosus" : {9: 'SM047'},
        "Xenuromys barbatus" : {9: 'SM010'},
        "Hydromys sp nov" : {9: 'REC9'},
        "Xeromys myoides" : {9: 'SM080'},
        "Pseudohydromys ellermani" : {9: 'SM073'},
        "Leptomys elegans" : {9: 'SM044'},
        "Pelomys isseli" : {9: 'SM068'},
        "Mus pos_ctrl_F" : {9: 'M44_F11'},
        "Mus pos_ctrl_E" : {9: 'M44_E11'},
        "Niviventer bukit" : {9: 'SM054'},
        "Genus sp nov" : {9: 'SM059'},
        "Saxatilomys paulinae" : {9: 'SM075'},
        "Crunomys sp." : {9: 'REC6'},
        "Microhydromys richardsoni" : {9: 'SM050'},
        "Uromys caudimaculatus" : {9: 'SM078'},
        "Mirzamys louiseae" : {9: 'SM051'},
        "Papagomys armandvillei" : {9: 'SM057'},
        "Chiromyscus chiropus" : {9: 'SM034'},
        "Pogonomelomys bruijni" : {9: 'REC26'},
        "Paraleptomys sp" : {9: 'SM065'},
        "Oenomys hypoxanthus" : {9: 'REC13'},
        "Bandicota indica" : {9: 'SM009'},
        "Rattus xanthurus" : {9: 'REC17'},
        "Lenomys meyeri" : {9: 'REC11'},
        "Thamnomys kempi" : {9: 'REC23'},
        "Parahydromys asper" : {9: 'SM058'},
        "Rattus argentiventer" : {9: 'SM042'},
        "Uromys sp nov" : {9: 'REC25'},
        "Otomys tropicalis" : {9: 'REC15'},
        "Niviventer cremoriventer" : {9: 'SM055'},
        "Otomys denti" : {9: 'REC14'},
        "Praomys jacksoni" : {9: 'REC31'},
        "Mus pos_ctrl_C" : {9: 'M44_C11'},
        "Mus pos_ctrl_B" : {9: 'M44_B11'},
        "Mus pos_ctrl_D1" : {9: 'M44_D11'},
        "Margaretamys christinae" : {10: 'SM061'},
        "Dasymys incomtus" : {10: 'REC29'},
        "Taeromys callitrichus" : {10: 'REC19'},
        "Hybomys lunaris" : {10: 'SM039'},
        "Sundamys annandalei" : {10: 'REC18'},
        "Nesokia indica" : {10: 'SM053'},
        "Macruromys major" : {10: 'SM045'},
        "Mus musculoides" : {10: 'REC30'},
        "Pelomys minor" : {10: 'REC16'},
        "Tarsomys apoensis" : {10: 'REC21'},
        "Batomys russatus" : {10: 'REC28'},
        "Halmaheramys bokimekot" : {10: 'REC22'},
        "Chiruromys vates" : {10: 'SM035'},
        "Chrotomys whiteheadi" : {10: 'REC34'},
        "Abeomelomys sevia" : {10: 'REC32'},
        "Berylmys mackenzii" : {10: 'SM011'},
        "Solomys salebrosus" : {10: 'SM076'},
        "Zelotomys woosnami" : {10: 'SM081'},
        "Kadarsanomys sodyi" : {10: 'REC_27'},
        "Mallomys rothschildi" : {10: 'SM046'},
        "Taeromys taerae" : {10: 'REC20'},
        "Vandeleuria oleracea" : {10: 'SM079'},
        "Mus pos_ctrl_A" : {10: 'M44_A12'},
        "Mus pos_ctrl_G" : {10: 'M44_G11'},
        "Mus pos_ctrl_D2" : {10: 'M44_D11'},
        "Conilurus albipes NMV c7585" : {11: '53930_HTVLKBCX2_TGCGTCC', 12: '53930_HTVLKBCX2_TGCGTCC'},
        "Conilurus penicillatus M14056" : {11: '53920_HTVLWBCX2_GCTCGAA', 12: '53920_HTVLWBCX2_GCTCGAA'},
        "Leggadina forresti WAMM62323" : {11: '52918_AH7T2JBCX2_CTGCGAC', 12: '52918_AH7T7NBCX2_CTGCGAC'},
        "Leggadina lakedownensis WAMM21623" : {11: '52919_AH7T2JBCX2_ACGTATG', 12: '52919_AH7T7NBCX2_ACGTATG'},
        "Leporillus apicalis C90" : {11 : "NA", 12 : "NA"},
        "Leporillus conditor ABTC13335" : {11 : "NA", 12 : "NA"},
        "Mastacomys fuscus M13957" : {11: 'NA', 12: 'NA'},
        "Mastacomys fuscus NMV C37546" : {11: 'NA', 12: 'NA'},
        "Mesembriomys gouldii ABTC7449" : {11: '53919_HTVLKBCX2_CTCGATG', 12: '53919_HTVLKBCX2_CTCGATG'},
        "Mesembriomys macrurus ABTC7337" : {11: '53918_HTVLWBCX2_ATGGAGA', 12: '53918_HTVLWBCX2_ATGGAGA'},
        "Notomys alexis U1308" : {11: '52920_AH7T2JBCX2_ATACTGA', 12: '52920_AH7T7NBCX2_ATACTGA'},
        "Notomys amplus NMV C512" : {11: '53926_HTVLWBCX2_TTGGATC', 12: '53926_HTVLWBCX2_TTGGATC'},
        "Notomys aquilo M 32455" : {11: '52921_AH7T2JBCX2_TACTTAG', 12: '52921_AH7T7NBCX2_TACTTAG'},
        "Notomys cervinus M22857" : {11: '52922_AH7T2JBCX2_AAGCTAA', 12: '52922_AH7T7NBCX2_AAGCTAA'},
        "Notomys fuscus M22830" : { 11: "NA", 12: "NA"},
        "Notomys longicaudatus C6278" : {11: '52956_BH7T33BCX2_GGTCAAG', 12: '52956_BH7T77BCX2_GGTCAAG'},
        "Notomys macrotis ZD 1841 1167" : {11: '53929_HTVLKBCX2_AGGTACC', 12: '53929_HTVLKBCX2_AGGTACC'},
        "Notomys mitchelli ABTC94521" : {11: 'NA', 12: 'NA'},
        "Notomys mitchellii M21518" : {11: 'NA', 12: 'NA'},
        "Pseudomys patrius JM10865" : {11: '52940_BH7T33BCX2_CCAACCT', 12: '52940_BH7T77BCX2_CCAACCT'},
        "Pseudomys pilligaensis ABTC18120" : {11: '52942_BH7T33BCX2_AGAATTA', 12: '52942_BH7T77BCX2_AGAATTA'},
        "Pseudomys shortridgei M7890" : {11: 'NA', 12: 'NA'},
        "Pseudomys shortridgei M62127" : {11: 'NA', 12: 'NA'},
        "Pseudomys shortridgei Z25113" : {11: 'NA', 12: 'NA'},
        "Rattus colletti RAT25" : {11: '52951_BH7T33BCX2_GCTAATC', 12: '52951_BH7T77BCX2_GCTAATC'},
        "Rattus tunneyi RAT130" : {11: '52952_BH7T33BCX2_GACTTCT', 12: '52952_BH7T77BCX2_GACTTCT'},
        "Zyzomys argurus ABTC61630" : {11: '52946_BH7T33BCX2_AACGACC', 12: '52946_BH7T77BCX2_AACGACC'},
        "Zyzomys maini ABTC07900" : {11: '52947_BH7T33BCX2_CCAGCGG', 12: '52947_BH7T77BCX2_CCAGCGG'},
        "Zyzomys palatalis ABTC30744" : {11: '52949_BH7T33BCX2_TGGCAAT', 12: '52949_BH7T77BCX2_TGGCAAT'},
        "Zyzomys pedunculatus Z34925" : {11: '52948_BH7T33BCX2_TAGTTCC', 12: '52948_BH7T77BCX2_TAGTTCC'},
        "Zyzomys woodwardi WAMM21724" : {11: '52950_BH7T33BCX2_CGTATAT', 12: '52950_BH7T77BCX2_CGTATAT'},
        "Pseudomys albocinereus WAMM18855" : {11: '52930_AH7T2JBCX2_AACCTGC', 12: '52930_AH7T7NBCX2_AACCTGC'},
        "Pseudomys apodemoides M16672" : {11: '52931_AH7T2JBCX2_GACGATT', 12: '52931_AH7T7NBCX2_GACGATT'},
        "Pseudomys auritus 1846 4 4 67" : {11: '53928_HTVLKBCX2_TAATGCG', 12: '53928_HTVLWBCX2_TAATGCG'},
        "Pseudomys australis M25541" : {11: '52932_AH7T2JBCX2_TAGGCCG', 12: '52932_AH7T7NBCX2_TAGGCCG'},
        "Pseudomys bolami ABTC08077" : {11: 'NA', 12: 'NA'},
        "Pseudomys bolami ABTC107389" : {11: 'NA', 12: 'NA'},
        "Pseudomys calabyi U4324" : {11: 'NA', 12: 'NA'},
        "Pseudomys calabyi WAMM56280" : {11: 'NA', 12: 'NA'},
        "Pseudomys chapmani WAMM29440" : {11: '52926_AH7T2JBCX2_TCAGCTT', 12: '52926_AH7T7NBCX2_TCAGCTT'},
        "Pseudomys delicatulus JM18363" : {11: 'NA', 12: 'NA'},
        "Pseudomys delicatulus M29247" : {11: 'NA', 12: 'NA'},
        "Pseudomys delicatulus U1509" : {11: 'NA', 12: 'NA'},
        "Pseudomys delicatulus WAMM29247" : {11: 'NA', 12: 'NA'},
        "Pseudomys desertor ABTC41464" : {11: '52925_AH7T2JBCX2_GTCCGGC', 12: '52925_AH7T7NBCX2_GTCCGGC'},
        "Pseudomys fieldi ABTC08164" : {11: '52941_BH7T33BCX2_GCAGAAG', 12: '52941_BH7T77BCX2_GCAGAAG'},
        "Pseudomys fumeus ABTC08168" : {11: '52955_BH7T33BCX2_AGCAGGT', 12: '52955_BH7T77BCX2_AGCAGGT'},
        "Pseudomys gouldii C955" : {11: '52955_BH7T33BCX2_AGCAGGT', 12: '52955_BH7T77BCX2_AGCAGGT'},
        "Pseudomys gracilicaudatus ABTC08163" : {11: '52934_AH7T2JBCX2_TTCAACC', 12: '52934_AH7T7NBCX2_TTCAACC'},
        "Pseudomys hermannsburgensis ABTC08067" : {11: '52943_BH7T33BCX2_CAGCATC', 12: '52943_BH7T77BCX2_CAGCATC'},
        "Pseudomys higginsi UC1421" : {11: '52953_BH7T33BCX2_GTACTAT', 12: '52953_BH7T77BCX2_GTACTAT', 13: '53925_HTVLKBCX2_ACTATCA', 14: '53925_HTVLWBCX2_ACTATCA'},
        "Pseudomys johnsoni ABTC08053" : {11: '52935_AH7T2JBCX2_TTAACTC', 12: '52935_AH7T7NBCX2_TTAACTC'},
        "Pseudomys nanus U1448" : {11: '52936_AH7T2JBCX2_TAGTCTA', 12: '52936_AH7T7NBCX2_TAGTCTA'},
        "Pseudomys novaehollandiae ABTC08140" : {11: 'NA', 12: 'NA'},
        "Pseudomys novaehollandiae NMV C22127" : {11: 'NA', 12: 'NA'},
        "Pseudomys occidentalis ABTC08043" : {11: '52939_BH7T33BCX2_AGCCTTG', 12: '52939_BH7T77BCX2_AGCCTTG'},
        "Pseudomys oralis RAT7" : {11: '52928_AH7T2JBCX2_GCCTACG', 12: '52928_AH7T7NBCX2_GCCTACG'}
    };




    return seq_run_ids, spec_ids, specs_ordered, spec_abbr, basedirs, spec_ids_new;



